site_name: Waste collection Gmina Środa Śląska
site_url: https://waste-collection-gmina-sroda-slaska.sciana.pro

copyright: Copyright &copy; 2025 sciana.pro

repo_url: https://github.com/ksciana/waste_collection

theme:
  icon:
    logo: material/truck-fast
  favicon: assets/icon.svg
  name: material
  custom_dir: overrides
  palette:
    primary: green
    accent: green
  font:
    text: Source Sans 3
  language: pl
  features:
    - navigation.tabs

nav:
  - 'Home': index.md
  - 'API': api.md

extra:
  social:
    - icon: material/home
      link: https://waste-collection.sciana.pro
    - icon: material/github
      link: https://github.com/ksciana/waste_collection
    - icon: material/coffee
      link: https://buycoffee.to/ksciana
    analytics:
    provider: google
    property: G-PP3RV1FM30
  consent:
    title: Dbamy o Twoją prywatność
    description: >- 
      Używamy plików cookie również do rozpoznawania Twoich powtarzających się wizyt i preferencji
      co do pomiaru efektywności naszej storny i tego, czy użytkownicy znaleźć to, czego szukają. Za Twoją zgodą pomagasz nam ulepszyć naszą stronę.
    actions:
      - accept
      - manage

plugins:
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg